- name: Check if snapd is installed
  ansible.builtin.package_facts:

- name: Stop snapd services if snapd is installed
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - snapd.service
    - snapd.socket
    - snapd.seeded.service
  when: "'snapd' in ansible_facts.packages"
