- name: Install libasound dependency
  ansible.builtin.apt:
    name: libasound2t64
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Spotify client
  ansible.builtin.apt:
    name: "{{ spotify_package_name }}"
    state: present
  become: true
