---
- name: Add Spotify's GPG key
  ansible.builtin.apt_key:
    url: "{{ spotify_gpg_key_url }}"
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg
    state: present
  become: true

- name: Add Spotify repository
  ansible.builtin.apt_repository:
    repo: "{{ spotify_repo_url }}"
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true