---
- name: Install helm dependencies
  become: True
  apt:
    name:
      - apt-transport-https
    state: present

- name: Install helm GPG key
  become: True
  apt_key:
    url: "{{  apt_helm_key  }}"
    state: present

- name: Add helm Repository
  apt_repository:
    repo: "{{  apt_helm_repo  }}"
    state: present

- name: Install helm
  become: True
  apt:
    name: helm 
    state: present
    update_cache: yes
