---
# tasks file to install software easily via package manager

- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install software packages
  become: true
  package:
    name: "{{  software_packages  }}"
    state: present

- name: Remove unwanted Gnome packages
  become: true
  package:
    name: "{{  rm_gnome_pkgs  }}"
    state: absent
