---
# tasks file to install software easily via package manager

- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- import_tasks: fedora.yml
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install software packages
  become: true
  package:
    name: "{{  software_packages  }}"
    state: present