- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - uidmap
      - dbus-user-session
    state: present
  become: true