---
- include_tasks: install_required_apt_packages.yaml
- include_tasks: enable_rootless_containers.yaml
- include_tasks: download_and_extract_nerdctl.yaml
- include_tasks: set_apparmor_profile.yaml
- include_tasks: containerd_rootless_install.yaml
- include_tasks: enable_bash_completion.yaml