- name: Check if Obsidian is already installed
  ansible.builtin.shell: "dpkg-query -W -f='${Status}' obsidian | grep 'install ok installed'"
  register: obsidian_installed
  ignore_errors: true

- name: Get Installed Obsidian Version
  ansible.builtin.command: dpkg-query -W -f='${Version}' obsidian
  register: version_check
  when: obsidian_installed.rc == 0
  ignore_errors: true