- name: Check if Obsidian is installed
  ansible.builtin.include_tasks: check_if_obsidian_is_installed.yaml

- name: Fetch latest Obsidian version
  ansible.builtin.include_tasks: fetch_latest_obsidian_version.yaml

- name: Determine if reinstallation is required
  ansible.builtin.set_fact:
    reinstall_required: "{{ obsidian_version != installed_version }}"

- name: Remove Obsidian - Ubuntu
  when: uninstall_obsidian and obsidian_installed.rc == 0
  ansible.builtin.include_tasks: remove_ubuntu.yaml

- name: Install or Update Ubuntu
  when: not uninstall_obsidian
  ansible.builtin.include_tasks: install_obsidian_ubuntu.yaml

