- name: Check if Obsidian is already installed
  ansible.builtin.command: dpkg-query -W -f='${Version}' obsidian
  register: obsidian_installed
  ignore_errors: true

- name: Parse installed Obsidian Version
  ansible.builtin.set_fact:
    installed_version: "{{ obsidian_installed.stdout if obsidian_installed.rc == 0 else '' }}"

- name: Remove Obsidian - Ubuntu
  when: uninstall_obsidian and obsidian_installed.rc == 0
  ansible.builtin.include_tasks: remove_ubuntu.yaml

- name: Install or Update Ubuntu
  when: not uninstall_obsidian
  ansible.builtin.include_tasks: install_or_update_ubuntu.yaml

