- name: Ensure 32-bit architecture is enabled
  ansible.builtin.command: dpkg --add-architecture i386
  become: true
  register: add_arch
  changed_when: add_arch.rc == 0

- name: Update package cache after adding i386 architecture
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: add_arch.changed

- name: Ensure Steam dependencies are installed
  ansible.builtin.apt:
    name:
      - libc6
      - libc6:i386
      - libegl1:i386
      - libgbm1:i386
      - libgl1-mesa-dri:i386
      - libgl1:i386
      - steam-libs-amd64:amd64
      - steam-libs-i386:i386
    state: present
    update_cache: true
  become: true