---
# Install VS Code on Ubuntu
- name: Update Software cache for apt
  become: true
  apt:
    update_cache: yes
  changed_when: False

- name: Install VS Code GPG Key
  apt_key:
    url: "{{ vscode_gpg_url }}"
    state: present

- name: Import VS Code apt repository
  become: True
  apt_repository:
    repo: "{{  vscode_apt_repository  }}"
    state: present

- name: Update apt cache and Install apt-transport-https package
  become: True
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Install VS Code via apt
  become: True
  apt:
    name: code
    state: present