---
# Tasksfile to install the config-files to the workstation

- name: Checkout the Dotfile Repo into a temporary folder
  git:
    repo: "{{  https_git_dotfile_repo  }}"
    dest: "{{  dotfiles_location  }}"
    version: "master"
  register: dotfiles_git_temp


- name: Find the installation shell script
  find:
    paths: "{{  dotfiles_location  }}"
    file_type: file
    patterns: '*.sh'
  register: installation_file

- name: Install dotfiles
  command:
    chdir: "{{  dotfiles_location  }}"
    cmd: "{{  installation_file  }}"
    creates: "{{  dotfiles_location  }}"

- name: Install python-psutil package
  become: true
  apt:
    name: python-psutil
    state: present

- name: Disable Mouse Acceleration Gnome-Desktop
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "flat"
  tags: mouse-accel

- name: Set touchpad Profile for LapTop
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/click-method"
    value: "fingers"

- name: Remove DotFile temporary folder
  become: true
  file:
    path: "{{  dotfiles_location  }}"
    state: absent
  when: dotfiles_git_temp.path is defined
