---
# Tasksfile to install the config-files to the workstation

- name: Create User with SSH key
  user:
    name: vagrant
    generate_ssh_key: yes


- name: Checkout the Dotfile Repo into a temporary folder
  git:
    repo: "{{  https_git_dotfile_repo  }}"
    dest: "{{  dotfiles_location  }}"
    version: "master"


- name: Find the installation shell script
  find:
    paths: "{{  dotfiles_location  }}"
    file_type: file
    patterns: '*.sh'
  register: installation_file

- name: Install dotfiles
  script:
    chdir: "{{  dotfiles_location  }}"
    cmd: "{{  installation_file  }}"