---
# Tasksfile to install the config-files to the workstation

- name: Create User with SSH key
  user:
    name: vagrant
    generate_ssh_key: yes


- name: Checkout the Dotfile Repo into a temporary folder
  git:
    repo: "{{  https_git_dotfile_repo  }}"
    dest: "{{  dotfiles_location  }}"
    version: "master"
  register: dotfiles_git_temp


- name: Find the installation shell script
  find:
    paths: "{{  dotfiles_location  }}"
    file_type: file
    patterns: '*.sh'
  register: installation_file

- name: Install dotfiles
  script:
    chdir: "{{  dotfiles_location  }}"
    cmd: "{{  installation_file  }}"

- name: Disable Mouse Acceleration
  templates:
      src: "50-mouse-acceleration.conf"
      dest: "/etc/X11/xorg.conf.d/50-mouse-acceleration.conf"
      mode: '0644'

- name: Remove DotFile temporary folder
  file:
    path: "{{  dotfiles_location  }}"
    state: absent
  when: dotfiles_git_temp.path is defined