---
# tasks file for python3 settings

- name: Install Python-pip
  become: true
  package:
    name:
      - python3-pip
    state: latest
  tags:
    - python

- name: Update pip
  become: true
  pip:
    name: pip
    extra_args: --upgrade
  tags:
    - python

- name: Update pip3
  become: true
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade
  tags:
    - python

- name: Install Jupyter Notebook
  pip:
    name: notebook
    executable: pip3
  tags:
    - python
