---
# tasks file for python3 settings

- name: Install Python-pip
  become: true
  package:
    name:
      - python-pip
      - python3-pip
    state: latest

- name: Update pip3
  become: true
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade