---
# tasks file for python3 settings

- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- import_tasks: fedora.yml
  become: true
  when: ansible_os_family == 'RedHat'

- name: Update pip3
  become: true
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade