- name: Set Admin Password
  block:
  - name: Extract initial admin password
    command: "nerdctl exec nexus cat /nexus-data/admin.password"
    register: extract_admin_password
    failed_when: not extract_admin_password.stdout
    ignore_errors: True

  - name: Set default_admin_password
    set_fact:
      default_admin_password: "{{ extract_admin_password.stdout }}"
    when: extract_admin_password is succeeded

  - name: Change admin password
    ansible.builtin.uri:
      method: PUT
      url: "{{ nexus_rest_api }}/v1/security/users/admin/change-password"
      user: "admin"
      password: "{{ default_admin_password }}"
      force_basic_auth: true
      headers:
        Content-Type: text/plain
      body: "admin"
      validate_certs: no
      status_code: [200, 202, 204]
    when: default_admin_password is defined
