- name: Create nexus directory
  ansible.builtin.file:
    path: "{{ nexus_work_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create Nexus compose file
  template:
    src: "{{ nexus_compose_file }}"
    dest: "{{ nexus_work_dir }}/{{ nexus_compose_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"