---
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    command: /sbin/init
    user: root
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    privileged: true
    command: /sbin/init
    user: root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
