spotify_source_list_filename: "spotify"
spotify_gpg_key_url: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
spotify_gpg_asc_key_path: "/etc/apt/keyrings/{{ spotify_source_list_filename }}.asc"
spotify_package_name: "spotify-client"