---
- name: Create temporary Downloadfolder
  tempfile:
    state: directory
    suffix: tmp_download
  register: temp_download_dir
  tags: cloud

- name: Install GCloud CLi
  import_tasks: gcloud.yml
  become: yes

- name: Install Azure CLI
  import_tasks: azure.yml
  become: yes

- name: Delete registerd temporary download directory
  file:
    path: "{{ temp_download_dir.path }}"
    state: absent
  when: temp_download_dir is defined
  tags: cloud