---
- name: Nexus3 ICE install
  hosts: all
  vars:
     - apt_repositories:
        - url: "http://de.archive.ubuntu.com/ubuntu/"
          name: "ubuntu"
          distribution: "focal jammy focal mantic xenial"
        - name: "dhor-ubuntu-myway-focal"
          url: "http://ppa.launchpad.net/dhor/myway/ubuntu"
          distribution: "focal"
        - name: "download_docker_com_linux_ubuntu"
          url: "https://download.docker.com/linux/ubuntu"
          distribution: "focal"
        - name: "flatpak-ubuntu-stable-focal"
          url: "http://ppa.launchpad.net/flatpak/stable/ubuntu"
          distribution: "focal"
        - name: "git-core-ubuntu-ppa-focal"
          url: "http://ppa.launchpad.net/git-core/ppa/ubuntu"
          distribution: "focal"
        - name: "helkaluin-ubuntu-webp-pixbuf-loader-focal"
          url: "http://ppa.launchpad.net/helkaluin/webp-pixbuf-loader/ubuntu"
          distribution: "focal"
        - name: "microsoft-prod"
          url: "https://packages.microsoft.com/ubuntu/20.04/prod"
          distribution: "focal"
        - name: "obsproject-ubuntu-obs-studio-focal"
          url: "http://ppa.launchpad.net/obsproject/obs-studio/ubuntu"
          distribution: "focal"
        - name: "packages_microsoft_com_repos_vscode"
          url: "https://packages.microsoft.com/repos/vscode"
          distribution: "stable"
        - name: "signal-xenial"
          url: "https://updates.signal.org/desktop/apt"
          distribution: "xenial"
        - name: "teams"
          url: "https://packages.microsoft.com/repos/ms-teams"
          distribution: "stable"
        - name: "ubuntuhandbook1-ubuntu-apps-focal"
          url: "http://ppa.launchpad.net/ubuntuhandbook1/apps/ubuntu"
          distribution: "focal"
        - name: "vscode"
          url: "http://packages.microsoft.com/repos/code"
          distribution: "stable"
  roles:
    - nexus