---
- name: Remove old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
    state: absent


- name: Install Docker requirements and update the apt cache
  become: True
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: True


- name: Add docker GPG key
  become: True
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present


- name: Add the Docker apt repository
  become: True
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: True