---
# tasks file to install Docker via the package manager

- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install the Docker-Engine - Community and containerd
  become: True
  package:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
