---
# tasks file to install Docker via the package manager

- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- import_tasks: fedora.yml
  become: true
  when: ansible_os_family == 'RedHat'