---
- name: Update APT package list
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove unwanted packages
  ansible.builtin.apt:
    name:
      - nano
    state: absent

- name: Install basic dev packages
  ansible.builtin.apt:
    pkg:
    - git
    - jq
    - tree
    - vim
    - python3-pip
    - openssh-server
    - openssh-client

- name: Install GUI / programms packages
  ansible.builtin.apt:
    pkg:
    - firefox