---
- name: Update APT package list
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - git
    - jq
    - firefox-esr

# To Install

# Remove
# Nano

