- name: Add Mozilla's GPG key
  ansible.builtin.get_url:
    url: "{{ mozilla_gpg_key_url }}"
    dest: "{{ mozilla_gpg_asc_key_path }}"

- name: Add Mozillas repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ mozilla_gpg_asc_key_path }}] https://packages.mozilla.org/apt mozilla main
    state: present
    filename: mozilla
  become: true